import { useEffect, useMemo, useState } from "react";
import { Brain, ExternalLink, LockKeyhole, Radar, TrendingUp } from "lucide-react";
import { trpc } from "@/lib/trpc";
import { Card } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Select,SelectContent,SelectItem,SelectTrigger,SelectValue } from "@/components/ui/select";
import { Tabs,TabsContent,TabsList,TabsTrigger } from "@/components/ui/tabs";

const warning="Cette analyse est générée automatiquement à partir de documents officiels publics. Elle ne remplace pas l'avis d'un expert réglementaire qualifié. Vérifiez les sources avant toute décision.";
const impactColor:Record<string,string>={eleve:"bg-red-100 text-red-800",moyen:"bg-amber-100 text-amber-800",faible:"bg-blue-100 text-blue-800"};
function Empty({children}:{children:string}){return <div className="rounded-xl border border-dashed p-8 text-center text-sm text-muted-foreground">{children}</div>}
export default function IntelligenceSectorielle(){
 const {data:refs=[]}=trpc.intelligence.referentials.useQuery();const [refId,setRefId]=useState("");useEffect(()=>{if(!refId&&refs.length)setRefId(String(refs.find((r:any)=>r.code==="MDR")?.id??refs[0].id));},[refs,refId]);
 const selected=refs.find((r:any)=>String(r.id)===refId);const {data:access}=trpc.intelligence.access.useQuery();
 const {data:trendData}=trpc.intelligence.trends.useQuery({referentialId:Number(refId),periodDays:90},{enabled:Boolean(refId)});const {data:signals=[]}=trpc.intelligence.signals.useQuery({referential:selected?.code??"MDR"});
 const {data:briefings=[]}=trpc.intelligence.briefings.useQuery({referential:selected?.code??"MDR"},{enabled:Boolean(access?.canUseSectorIntelligence),retry:false});const trends=trendData?.trends;const maxProcess=Math.max(1,...(trends?.topNCProcessus??[]).map((x:any)=>x.tauxNC));
 const lastUpdate=useMemo(()=>briefings.length?new Date(Math.max(...briefings.map((b:any)=>new Date(b.generatedAt).getTime()))):null,[briefings]);
 return <div className="mx-auto max-w-[1500px] space-y-7 py-3"><header className="flex flex-col justify-between gap-4 lg:flex-row lg:items-end"><div><p className="flex items-center gap-2 text-sm font-medium text-violet-700"><Brain className="h-4 w-4"/>Radar réglementaire et qualité</p><h1 className="mt-1 text-3xl font-bold">Intelligence Sectorielle DM</h1><p className="mt-2 text-muted-foreground">Tendances d'audit, analyses sectorielles et signaux faibles.</p></div><div className="flex items-center gap-3"><Select value={refId} onValueChange={setRefId}><SelectTrigger className="w-64 bg-white"><SelectValue placeholder="Référentiel"/></SelectTrigger><SelectContent>{refs.map((r:any)=><SelectItem key={r.id} value={String(r.id)}>{r.code} — {r.name}</SelectItem>)}</SelectContent></Select><Badge variant="outline">{lastUpdate?`Mis à jour le ${lastUpdate.toLocaleDateString("fr-FR")}`:"En attente du briefing hebdomadaire"}</Badge></div></header>
 <section className="space-y-4"><div><h2 className="text-xl font-semibold">Vos points de vigilance — basé sur vos audits</h2>{trends?.avertissement&&<p className="mt-1 text-sm text-amber-700">{trends.avertissement}</p>}</div>{trendData?.auditCount<3?<Empty>Complétez au moins 3 audits pour voir vos tendances personnalisées.</Empty>:<div className="grid gap-5 xl:grid-cols-3"><Card className="p-5"><h3 className="font-semibold">NC les plus fréquentes</h3><div className="mt-3 divide-y">{trends?.topNCQuestions.slice(0,5).map((x:any)=><div className="py-3" key={x.questionKey}><p className="line-clamp-2 text-sm font-medium">{x.questionExtrait}</p><div className="mt-1 flex justify-between text-xs text-muted-foreground"><span>{x.processus||"—"}</span><strong>{x.tauxNC}% NC</strong></div></div>)}</div></Card><Card className="p-5"><h3 className="font-semibold">Processus les plus défaillants</h3><div className="mt-4 space-y-4">{trends?.topNCProcessus.slice(0,6).map((x:any)=><div key={x.processus}><div className="mb-1 flex justify-between text-sm"><span>{x.processus}</span><strong>{x.tauxNC}%</strong></div><div className="h-2 rounded bg-slate-100"><div className="h-2 rounded bg-red-500" style={{width:`${x.tauxNC/maxProcess*100}%`}}/></div></div>)}</div></Card><Card className="p-5"><h3 className="font-semibold">Évolution de la conformité</h3><div className="mt-5 flex h-48 items-end gap-3">{trends?.evolutionConformite.map((x:any)=><div key={x.mois} className="flex flex-1 flex-col items-center gap-2"><span className="text-xs font-medium">{x.tauxConformite}%</span><div className="w-full rounded-t bg-emerald-500" style={{height:`${Math.max(4,x.tauxConformite*1.4)}px`}}/><span className="text-[10px] text-muted-foreground">{x.mois.slice(5)}</span></div>)}</div></Card></div>}</section>
 <section className="space-y-4"><h2 className="text-xl font-semibold">Analyses sectorielles</h2>{!access?.canUseSectorIntelligence?<Card className="flex items-center gap-4 border-violet-200 bg-violet-50 p-6"><LockKeyhole className="h-7 w-7 text-violet-700"/><div><h3 className="font-semibold">Réservé aux plans Pro et Enterprise</h3><p className="text-sm text-muted-foreground">Les tendances personnelles restent accessibles sur votre plan.</p></div></Card>:briefings.length?<Tabs defaultValue="audit_trends"><TabsList><TabsTrigger value="audit_trends">Tendances audit</TabsTrigger><TabsTrigger value="safety_alerts">Alertes sécurité</TabsTrigger><TabsTrigger value="regulatory_updates">Évolutions à venir</TabsTrigger><TabsTrigger value="best_practices">Bonnes pratiques</TabsTrigger></TabsList>{["audit_trends","safety_alerts","regulatory_updates","best_practices"].map(topic=><TabsContent key={topic} value={topic} className="space-y-4">{briefings.filter((b:any)=>b.topic===topic).map((b:any)=>{const c=b.content;return <Card key={b.id} className="p-6"><div className="flex items-start justify-between gap-4"><div><Badge className={impactColor[c.pointsCles?.[0]?.impact]||""}>{c.tendances?.[0]?.signal?`Signal ${c.tendances[0].signal}`:"Analyse"}</Badge><h3 className="mt-3 text-xl font-semibold">{c.titre}</h3><p className="mt-2 text-sm text-muted-foreground">{c.resume}</p></div><Badge variant="outline">Confiance : {c.niveauConfiance}</Badge></div><div className="mt-5 space-y-3">{c.pointsCles?.map((p:any,i:number)=><div key={i} className="rounded-lg bg-slate-50 p-3"><strong className="text-sm">{p.titre}</strong><p className="mt-1 text-sm">{p.description}</p><p className="mt-1 text-xs text-blue-700">Source : {p.source}</p></div>)}</div><div className="mt-5 rounded-lg border border-amber-200 bg-amber-50 p-3 text-xs text-amber-900">⚠️ {c.avertissement||warning}</div></Card>})}</TabsContent>)}</Tabs>:<Empty>Aucun briefing valide. Le worker hebdomadaire générera les analyses après validation de la migration 0048.</Empty>}</section>
 <section className="space-y-4"><div className="flex items-center gap-2"><Radar className="h-5 w-5 text-blue-700"/><h2 className="text-xl font-semibold">Sur le radar — évolutions à surveiller</h2></div>{signals.length?<div className="grid gap-4 lg:grid-cols-2">{signals.map((s:any)=><Card key={s.id} className="p-5"><div className="flex justify-between"><Badge variant={s.criticality==="action_required"?"destructive":"secondary"}>{s.criticality}</Badge><span className="text-xs text-muted-foreground">{s.publishedAt?new Date(s.publishedAt).toLocaleDateString("fr-FR"):"Date inconnue"}</span></div><h3 className="mt-3 font-semibold">{s.title}</h3><p className="mt-2 line-clamp-3 text-sm text-muted-foreground">{s.summary}</p><a className="mt-3 inline-flex items-center gap-1 text-sm text-blue-700" href={s.sourceUrl} target="_blank" rel="noreferrer">Source officielle <ExternalLink className="h-3 w-3"/></a></Card>)}</div>:<Empty>Aucun signal faible non traité pour ce référentiel.</Empty>}</section>
 {access?.canUseSectorBenchmark&&<section><div className="flex items-center gap-2"><TrendingUp className="h-5 w-5"/><h2 className="text-xl font-semibold">Votre positionnement</h2></div><Card className="mt-4 p-6"><p className="text-sm text-muted-foreground">Le benchmark anonymisé sera affiché dès que les cohortes satisfont les seuils de confidentialité.</p><p className="mt-3 text-xs">Ces comparaisons sont basées sur les utilisateurs QARA. Elles ne représentent pas l'ensemble du marché DM.</p></Card></section>}
 </div>;
}
