import { LegalPage, type LegalSection } from "./LegalPage";

const sections: LegalSection[] = [
  { id: "objet", title: "Objet et acceptation", content: <><p>Les présentes conditions encadrent l'accès et l'utilisation de QARA, plateforme SaaS B2B d'auto-évaluation de conformité réglementaire pour les dispositifs médicaux, éditée par NGANKEP NZETCHOUANG NICK, entrepreneur individuel exerçant sous le nom commercial N3 CONSEIL.</p><p>La création d'un compte implique l'acceptation expresse des présentes CGU. Elles peuvent être modifiées ; toute modification substantielle sera notifiée dans les conditions précisées par la politique de confidentialité.</p></> },
  { id: "service", title: "Description du service", content: <><p>QARA permet de préparer et documenter des audits, suivre des actions et générer des rapports au regard de sept référentiels : MDR, IVDR, FDA QMSR, MDSAP, ISO 13485, ISO 14971 et ISO 9001.</p><p>QARA est un outil d'aide à la décision et à la préparation. Ses contenus et rapports ne constituent ni un conseil juridique, ni une certification, ni une décision d'une autorité ou d'un organisme notifié.</p></> },
  { id: "compte", title: "Accès et compte utilisateur", content: <><p>L'utilisateur fournit des informations exactes, protège ses identifiants et signale sans délai toute utilisation non autorisée. Les modalités et fonctionnalités disponibles dépendent du plan FREE, PRO ou ENTERPRISE souscrit.</p></> },
  { id: "propriete", title: "Propriété intellectuelle", content: <><p>La plateforme, sa structure et ses éléments propres appartiennent à NGANKEP NZETCHOUANG NICK, exerçant sous le nom commercial N3 CONSEIL. Les textes réglementaires officiels restent soumis aux droits et conditions de leurs organismes émetteurs.</p><p>L'utilisateur conserve ses droits sur les données qu'il saisit et sur les rapports générés à partir de celles-ci, sous réserve des éléments préexistants de QARA et des sources officielles.</p></> },
  { id: "donnees", title: "Données et confidentialité", content: <><p>Le traitement des données est décrit dans la <a className="text-[#2558c7] underline" href="/politique-confidentialite">Politique de confidentialité</a>. QARA s'engage à ne pas divulguer les données d'audit, sauf instruction de l'utilisateur, nécessité technique encadrée ou obligation légale.</p></> },
  { id: "responsabilite", title: "Limitation de responsabilité", content: <><p>L'utilisateur demeure seul responsable de ses décisions et de sa conformité réglementaire. Il doit vérifier les sources, résultats, recommandations et résumés générés, notamment ceux assistés par intelligence artificielle.</p><p>Dans les limites autorisées par la loi, QARA ne garantit pas l'exhaustivité ni l'adéquation des résultats à une situation réglementaire particulière.</p></> },
  { id: "resiliation", title: "Résiliation", content: <><p>L'utilisateur peut résilier son abonnement et demander la fermeture de son compte depuis son espace ou à infos@n3-conseil.com. QARA peut suspendre ou résilier un compte en cas de violation grave, d'usage illicite, de risque de sécurité ou d'impayé, après information lorsque les circonstances le permettent.</p></> },
  { id: "droit", title: "Droit applicable et juridiction", content: <><p>Les présentes CGU sont soumises au droit français. Après tentative de résolution amiable et sous réserve des règles impératives applicables, tout litige relève des juridictions françaises territorialement compétentes.</p></> },
];

export default function CGU() { return <LegalPage title="Conditions Générales d'Utilisation" sections={sections} />; }
