import { LegalPage, type LegalSection } from "./LegalPage";

const sections: LegalSection[] = [
  { id: "responsable", title: "Responsable du traitement", content: <p>NGANKEP NZETCHOUANG NICK, entrepreneur individuel exerçant sous le nom commercial N3 CONSEIL, 5 place Ingres, étage 1, appartement 325, 37200 Tours, France. SIREN : 912 622 222 — SIRET : 912 622 222 00020. Contact RGPD : <a className="text-[#2558c7] underline" href="mailto:infos@n3-conseil.com">infos@n3-conseil.com</a>.</p> },
  { id: "donnees", title: "Données collectées", content: <ul className="list-disc pl-6"><li>identification : nom et email professionnel ;</li><li>données professionnelles : organisation, rôle et secteur ;</li><li>utilisation : audits, réponses, rapports et actions CAPA ;</li><li>navigation et sécurité : journaux techniques et adresse IP ;</li><li>facturation : traitée par Stripe, sans stockage des données de carte par QARA.</li></ul> },
  { id: "finalites", title: "Finalités et bases légales", content: <ul className="list-disc pl-6"><li>fourniture du service et veille réglementaire : exécution du contrat ;</li><li>sécurité et amélioration du service : intérêt légitime, après mise en balance ;</li><li>facturation et comptabilité : obligations légales ;</li><li>communications commerciales : consentement, retirable à tout moment.</li></ul> },
  { id: "conservation", title: "Durées de conservation", content: <ul className="list-disc pl-6"><li>compte : relation contractuelle puis 3 ans ;</li><li>audits : relation contractuelle puis 5 ans, sous réserve de la justification et des obligations applicables ;</li><li>journaux techniques : 90 jours ;</li><li>pièces de facturation : 10 ans.</li></ul> },
  { id: "destinataires", title: "Destinataires et sous-traitants", content: <p>Les données nécessaires peuvent être traitées par Railway (backend et base, région UE), Vercel (frontend et CDN mondial), Stripe (paiement), Resend (emails transactionnels), Cloudflare R2 (rapports) et leurs sous-traitants. Anthropic traite uniquement le contenu de documents officiels publics pour l'analyse de veille ; aucune donnée personnelle d'utilisateur ne doit lui être transmise.</p> },
  { id: "transferts", title: "Transferts hors Espace économique européen", content: <><p>Certains prestataires peuvent traiter des données hors EEE, notamment aux États-Unis. Les transferts sont encadrés, selon le prestataire et le flux, par une décision d'adéquation telle que le Cadre de protection des données UE–États-Unis lorsque le destinataire y est valablement certifié, ou par les clauses contractuelles types de la Commission européenne intégrées aux accords de traitement des données.</p><p>À la date de mise à jour, Vercel et Cloudflare déclarent s'appuyer sur le Cadre UE–États-Unis et/ou les clauses contractuelles types ; les accords de Railway, Stripe, Resend et Anthropic intègrent également des clauses contractuelles types ou mécanismes équivalents applicables. Ces garanties sont réévaluées en cas de changement de prestataire ou de cadre juridique.</p></> },
  { id: "droits", title: "Droits des personnes", content: <><p>Vous disposez des droits d'accès (art. 15), rectification (art. 16), effacement (art. 17), limitation (art. 18), portabilité (art. 20) et opposition (art. 21), dans les conditions prévues par le RGPD.</p><p>Contact : <a className="text-[#2558c7] underline" href="mailto:infos@n3-conseil.com">infos@n3-conseil.com</a>. Vous pouvez également saisir la <a className="text-[#2558c7] underline" href="https://www.cnil.fr" target="_blank" rel="noreferrer">CNIL</a>.</p></> },
  { id: "cookies", title: "Cookies et stockages locaux", content: <><p>QARA utilise un cookie de session d'authentification strictement nécessaire et un cookie technique mémorisant l'état de la barre latérale. Ils ne nécessitent pas de consentement.</p><p>Le stockage local du navigateur conserve uniquement des préférences d'interface et d'onboarding (langue, thème, marché, rôle, dimensions de navigation). Aucun outil d'analyse publicitaire n'a été identifié lors de l'audit du 1er septembre 2026.</p></> },
  { id: "modifications", title: "Modifications", content: <p>Toute modification substantielle de la présente politique sera annoncée par email ou dans le service avant son entrée en vigueur. La date de mise à jour figure en haut de page.</p> },
];

export default function PolitiqueConfidentialite() { return <LegalPage title="Politique de confidentialité" sections={sections} />; }
